
name: Main

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: install-deps
      run: sudo apt-get update && sudo apt-get install build-essential
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install
    - name: run tests
      run: npm test